/*
projecteuler.net problem2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>


void main(){

	int max=4000000; //don't exceed four million

	
	//initialize fibonacci array, with index 'n'
	int fib_array[200];
	fib_array[0]=1;
	fib_array[1]=2;
	int n=1;

	int result = fib_array[1]; //2 is the first even term of the sequence

	while (fib_array[n]<max)
	{
		n++;
		fib_array[n]=fib_array[n-1]+fib_array[n-2];
		if (fib_array[n]%2==0)
		{
			result+=fib_array[n];
		}

	}

	std::cout << "Result is: " << result << std::endl;
}